# Generated by Django 5.0 on 2024-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkslibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
