# Generated by Django 5.0 on 2024-08-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkslibrary', '0002_resource_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('order',), 'verbose_name': 'ресурс', 'verbose_name_plural': 'ресурсы'},
        ),
    ]
