# Generated by Django 5.0.1 on 2024-08-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookslibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
