# Generated by Django 5.0.1 on 2024-08-05 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookslibrary', '0002_remove_book_language_delete_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='eBooks', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'djvu'))], verbose_name='экземпляр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon_books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста'),
        ),
    ]
